TERMUX_PKG_HOMEPAGE=https://github.com/tsujan/FeatherNotes
TERMUX_PKG_DESCRIPTION="Lightweight Qt Notes-Manager for Linux"
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_MAINTAINER="Yisus7u7"
TERMUX_PKG_VERSION=0.9.0
TERMUX_PKG_SRCURL=https://github.com/Yisus7u7/shpkg-builds/releases/download/${TERMUX_PKG_VERSION}/feathernotes-${TERMUX_PKG_VERSION}.tar.xz
TERMUX_PKG_SHA256=cef7262cdb9ca56c0ee1ffefb8373f8cd01f33c844f011338f067f0f88175c0c
TERMUX_PKG_DEPENDS="hicolor-icon-theme, qt5-qtbase, qt5-qtsvg, qt5-qtx11extras, hunspell, libx11"
TERMUX_PKG_BUILD_DEPENDS="qt5-qtbase-cross-tools, qt5-qttools-cross-tools"
